package kPsychoMod.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLauncher extends ModelBase {

   public ModelRenderer blockintake1;
   public ModelRenderer blockintake2;
   public ModelRenderer blockintake3;
   public ModelRenderer blockintake4;
   public ModelRenderer handle;
   public ModelRenderer barrel9;
   public ModelRenderer barrel10;
   public ModelRenderer barrel11;
   public ModelRenderer barrel12;
   public ModelRenderer barrel13;
   public ModelRenderer barrel14;
   public ModelRenderer barrel15;
   public ModelRenderer barrel16;
   public ModelRenderer barrel1;
   public ModelRenderer barrel8;
   public ModelRenderer barrel7;
   public ModelRenderer barrel2;
   public ModelRenderer barrel3;
   public ModelRenderer barrel6;
   public ModelRenderer barrel4;
   public ModelRenderer barrel5;
   public ModelRenderer scopeL;
   public ModelRenderer backright;
   public ModelRenderer backmiddle;
   public ModelRenderer backbottom;
   public ModelRenderer backtop;
   public ModelRenderer backleft;
   public ModelRenderer baselauncher;
   public ModelRenderer scopeR;


   public ModelLauncher() {
      this.textureWidth = 256;
      this.textureHeight = 256;
      this.blockintake1 = new ModelRenderer(this, 28, 2);
      this.blockintake1.addBox(-2.0F, -9.0F, -1.0F, 1, 2, 2);
      this.blockintake1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.blockintake1.setTextureSize(256, 256);
      this.blockintake1.mirror = true;
      this.setRotation(this.blockintake1, 0.0F, 0.0F, 0.0F);
      this.blockintake2 = new ModelRenderer(this, 28, 0);
      this.blockintake2.addBox(-2.0F, -9.0F, 1.0F, 4, 2, 1);
      this.blockintake2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.blockintake2.setTextureSize(256, 256);
      this.blockintake2.mirror = true;
      this.setRotation(this.blockintake2, 0.0F, 0.0F, 0.0F);
      this.blockintake3 = new ModelRenderer(this, 28, 0);
      this.blockintake3.addBox(1.0F, -9.0F, -1.0F, 1, 2, 2);
      this.blockintake3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.blockintake3.setTextureSize(256, 256);
      this.blockintake3.mirror = true;
      this.setRotation(this.blockintake3, 0.0F, 0.0F, 0.0F);
      this.blockintake4 = new ModelRenderer(this, 28, 0);
      this.blockintake4.addBox(-2.0F, -9.0F, -2.0F, 4, 2, 1);
      this.blockintake4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.blockintake4.setTextureSize(256, 256);
      this.blockintake4.mirror = true;
      this.setRotation(this.blockintake4, 0.0F, 0.0F, 0.0F);
      this.handle = new ModelRenderer(this, 44, 0);
      this.handle.addBox(-1.0F, -1.0F, -3.0F, 2, 4, 2);
      this.handle.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.handle.setTextureSize(256, 256);
      this.handle.mirror = true;
      this.setRotation(this.handle, 0.0F, 0.0F, 0.0F);
      this.barrel9 = new ModelRenderer(this, 0, 14);
      this.barrel9.addBox(-1.0F, -7.0F, 4.0F, 2, 1, 8);
      this.barrel9.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel9.setTextureSize(256, 256);
      this.barrel9.mirror = true;
      this.setRotation(this.barrel9, 0.0F, 0.0F, 0.0F);
      this.barrel10 = new ModelRenderer(this, 0, 33);
      this.barrel10.addBox(1.0F, -6.0F, 4.0F, 1, 1, 8);
      this.barrel10.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel10.setTextureSize(256, 256);
      this.barrel10.mirror = true;
      this.setRotation(this.barrel10, 0.0F, 0.0F, 0.0F);
      this.barrel11 = new ModelRenderer(this, 0, 23);
      this.barrel11.addBox(2.0F, -5.0F, 4.0F, 1, 2, 8);
      this.barrel11.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel11.setTextureSize(256, 256);
      this.barrel11.mirror = true;
      this.setRotation(this.barrel11, 0.0F, 0.0F, 0.0F);
      this.barrel12 = new ModelRenderer(this, 0, 42);
      this.barrel12.addBox(1.0F, -3.0F, 4.0F, 1, 1, 8);
      this.barrel12.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel12.setTextureSize(256, 256);
      this.barrel12.mirror = true;
      this.setRotation(this.barrel12, 0.0F, 0.0F, 0.0F);
      this.barrel13 = new ModelRenderer(this, 0, 51);
      this.barrel13.addBox(-1.0F, -2.0F, 4.0F, 2, 1, 8);
      this.barrel13.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel13.setTextureSize(256, 256);
      this.barrel13.mirror = true;
      this.setRotation(this.barrel13, 0.0F, 0.0F, 0.0F);
      this.barrel14 = new ModelRenderer(this, 0, 42);
      this.barrel14.addBox(-2.0F, -3.0F, 4.0F, 1, 1, 8);
      this.barrel14.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel14.setTextureSize(256, 256);
      this.barrel14.mirror = true;
      this.setRotation(this.barrel14, 0.0F, 0.0F, 0.0F);
      this.barrel15 = new ModelRenderer(this, 0, 23);
      this.barrel15.addBox(-3.0F, -5.0F, 4.0F, 1, 2, 8);
      this.barrel15.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel15.setTextureSize(256, 256);
      this.barrel15.mirror = true;
      this.setRotation(this.barrel15, 0.0F, 0.0F, 0.0F);
      this.barrel16 = new ModelRenderer(this, 0, 33);
      this.barrel16.addBox(-2.0F, -6.0F, 4.0F, 1, 1, 8);
      this.barrel16.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel16.setTextureSize(256, 256);
      this.barrel16.mirror = true;
      this.setRotation(this.barrel16, 0.0F, 0.0F, 0.0F);
      this.barrel1 = new ModelRenderer(this, 0, 14);
      this.barrel1.addBox(-1.0F, -7.0F, -12.0F, 2, 1, 8);
      this.barrel1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel1.setTextureSize(256, 256);
      this.barrel1.mirror = true;
      this.setRotation(this.barrel1, 0.0F, 0.0F, 0.0F);
      this.barrel8 = new ModelRenderer(this, 0, 33);
      this.barrel8.addBox(-2.0F, -6.0F, -12.0F, 1, 1, 8);
      this.barrel8.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel8.setTextureSize(256, 256);
      this.barrel8.mirror = true;
      this.setRotation(this.barrel8, 0.0F, 0.0F, 0.0F);
      this.barrel7 = new ModelRenderer(this, 0, 23);
      this.barrel7.addBox(-3.0F, -5.0F, -12.0F, 1, 2, 8);
      this.barrel7.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel7.setTextureSize(256, 256);
      this.barrel7.mirror = true;
      this.setRotation(this.barrel7, 0.0F, 0.0F, 0.0F);
      this.barrel2 = new ModelRenderer(this, 0, 33);
      this.barrel2.addBox(1.0F, -6.0F, -12.0F, 1, 1, 8);
      this.barrel2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel2.setTextureSize(256, 256);
      this.barrel2.mirror = true;
      this.setRotation(this.barrel2, 0.0F, 0.0F, 0.0F);
      this.barrel3 = new ModelRenderer(this, 0, 23);
      this.barrel3.addBox(2.0F, -5.0F, -12.0F, 1, 2, 8);
      this.barrel3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel3.setTextureSize(256, 256);
      this.barrel3.mirror = true;
      this.setRotation(this.barrel3, 0.0F, 0.0F, 0.0F);
      this.barrel6 = new ModelRenderer(this, 0, 42);
      this.barrel6.addBox(-2.0F, -3.0F, -12.0F, 1, 1, 8);
      this.barrel6.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel6.setTextureSize(256, 256);
      this.barrel6.mirror = true;
      this.setRotation(this.barrel6, 0.0F, 0.0F, 0.0F);
      this.barrel4 = new ModelRenderer(this, 0, 42);
      this.barrel4.addBox(1.0F, -3.0F, -12.0F, 1, 1, 8);
      this.barrel4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel4.setTextureSize(256, 256);
      this.barrel4.mirror = true;
      this.setRotation(this.barrel4, 0.0F, 0.0F, 0.0F);
      this.barrel5 = new ModelRenderer(this, 0, 51);
      this.barrel5.addBox(-1.0F, -2.0F, -12.0F, 2, 1, 8);
      this.barrel5.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.barrel5.setTextureSize(256, 256);
      this.barrel5.mirror = true;
      this.setRotation(this.barrel5, 0.0F, 0.0F, 0.0F);
      this.scopeL = new ModelRenderer(this, 52, 0);
      this.scopeL.addBox(3.0F, -7.0F, -4.0F, 3, 3, 6);
      this.scopeL.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.scopeL.setTextureSize(256, 256);
      this.scopeL.mirror = true;
      this.setRotation(this.scopeL, 0.0F, 0.0F, 0.0F);
      this.backright = new ModelRenderer(this, 0, 0);
      this.backright.addBox(-2.0F, -5.0F, 11.0F, 1, 2, 1);
      this.backright.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.backright.setTextureSize(256, 256);
      this.backright.mirror = true;
      this.setRotation(this.backright, 0.0F, 0.0F, 0.0F);
      this.backmiddle = new ModelRenderer(this, 28, 6);
      this.backmiddle.addBox(-1.0F, -5.0F, 11.0F, 2, 2, 1);
      this.backmiddle.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.backmiddle.setTextureSize(256, 256);
      this.backmiddle.mirror = true;
      this.setRotation(this.backmiddle, 0.0F, 0.0F, 0.0F);
      this.backbottom = new ModelRenderer(this, 0, 0);
      this.backbottom.addBox(-1.0F, -3.0F, 11.0F, 2, 1, 1);
      this.backbottom.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.backbottom.setTextureSize(256, 256);
      this.backbottom.mirror = true;
      this.setRotation(this.backbottom, 0.0F, 0.0F, 0.0F);
      this.backtop = new ModelRenderer(this, 0, 0);
      this.backtop.addBox(-1.0F, -6.0F, 11.0F, 2, 1, 1);
      this.backtop.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.backtop.setTextureSize(256, 256);
      this.backtop.mirror = true;
      this.setRotation(this.backtop, 0.0F, 0.0F, 0.0F);
      this.backleft = new ModelRenderer(this, 0, 0);
      this.backleft.addBox(1.0F, -5.0F, 11.0F, 1, 2, 1);
      this.backleft.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.backleft.setTextureSize(256, 256);
      this.backleft.mirror = true;
      this.setRotation(this.backleft, 0.0F, 0.0F, 0.0F);
      this.baselauncher = new ModelRenderer(this, 0, 0);
      this.baselauncher.addBox(-3.0F, -7.0F, -4.0F, 6, 6, 8);
      this.baselauncher.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.baselauncher.setTextureSize(256, 256);
      this.baselauncher.mirror = true;
      this.setRotation(this.baselauncher, 0.0F, 0.0F, 0.0F);
      this.scopeR = new ModelRenderer(this, 52, 0);
      this.scopeR.addBox(-6.0F, -7.0F, -4.0F, 3, 3, 6);
      this.scopeR.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.scopeR.setTextureSize(256, 256);
      this.scopeR.mirror = true;
      this.setRotation(this.scopeR, 0.0F, 0.0F, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, boolean isFirstPerson) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.blockintake1.render(f5);
      this.blockintake2.render(f5);
      this.blockintake3.render(f5);
      this.blockintake4.render(f5);
      this.handle.render(f5);
      this.barrel9.render(f5);
      this.barrel10.render(f5);
      this.barrel11.render(f5);
      this.barrel12.render(f5);
      this.barrel13.render(f5);
      this.barrel14.render(f5);
      this.barrel15.render(f5);
      this.barrel16.render(f5);
      this.barrel1.render(f5);
      this.barrel8.render(f5);
      this.barrel7.render(f5);
      this.barrel2.render(f5);
      this.barrel3.render(f5);
      this.barrel6.render(f5);
      this.barrel4.render(f5);
      this.barrel5.render(f5);
      if(isFirstPerson) {
         this.scopeL.render(f5);
      } else {
         this.scopeR.render(f5);
      }

      this.backright.render(f5);
      this.backmiddle.render(f5);
      this.backbottom.render(f5);
      this.backtop.render(f5);
      this.backleft.render(f5);
      this.baselauncher.render(f5);
   }

   private void setRotation(ModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
   }
}
